# Logistic Regression

1. area A,
2. perimeter P,
3. compactness C = 4*pi*A/P^2,
4. length of kernel,
5. width of kernel,
6. asymmetry coefficient
7. length of kernel groove.

In [1]:
import numpy as np
import pandas as pd

In [2]:
names = [
    'area',
    'perimeter',
    'compactness',
    'length',
    'width',
    'coefficient',
    'kernel groove',
    'class',
]

In [12]:
dataset = pd.read_csv('data/seeds_dataset.txt', sep='\t', header=None, names=names) #, on_bad_lines='warn')

In [13]:
dataset.head(10)

area  perimeter  compactness  length  width  coefficient  kernel groove  \
0  15.26      14.84       0.8710   5.763  3.312        2.221          5.220   
1  14.88      14.57       0.8811   5.554  3.333        1.018          4.956   
2  14.29      14.09       0.9050   5.291  3.337        2.699          4.825   
3  13.84      13.94       0.8955   5.324  3.379        2.259          4.805   
4  16.14      14.99       0.9034   5.658  3.562        1.355          5.175   
5  14.38      14.21       0.8951   5.386  3.312        2.462          4.956   
6  14.69      14.49       0.8799   5.563  3.259        3.586          5.219   
7  14.11      14.10       0.8911   5.420  3.302        2.700          5.000   
8  16.63      15.46       0.8747   6.053  3.465        2.040          5.877   
9  16.44      15.25       0.8880   5.884  3.505        1.969          5.533   

   class  
0      1  
1      1  
2      1  
3      1  
4      1  
5      1  
6      1  
7      1  
8      1  
9      1

In [18]:
dataset.shape

(210, 8)

In [20]:
dataset.dropna(how='any')

area  perimeter  compactness  length  width  coefficient  kernel groove  \
0    15.26      14.84       0.8710   5.763  3.312        2.221          5.220   
1    14.88      14.57       0.8811   5.554  3.333        1.018          4.956   
2    14.29      14.09       0.9050   5.291  3.337        2.699          4.825   
3    13.84      13.94       0.8955   5.324  3.379        2.259          4.805   
4    16.14      14.99       0.9034   5.658  3.562        1.355          5.175   
..     ...        ...          ...     ...    ...          ...            ...   
205  12.19      13.20       0.8783   5.137  2.981        3.631          4.870   
206  11.23      12.88       0.8511   5.140  2.795        4.325          5.003   
207  13.20      13.66       0.8883   5.236  3.232        8.315          5.056   
208  11.84      13.21       0.8521   5.175  2.836        3.598          5.044   
209  12.30      13.34       0.8684   5.243  2.974        5.637          5.063   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
205      3  
206      3  
207      3  
208      3  
209      3  

[210 rows x 8 columns]

In [21]:
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [22]:
X

array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
       [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
       [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]])

In [23]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=123)

In [27]:
X_train.shape

(147, 7)

In [28]:
X_test.shape

(63, 7)

In [29]:
from sklearn.linear_model import LogisticRegression

In [35]:
import warnings
warnings.filterwarnings('ignore')

In [36]:
lr = LogisticRegression()

In [37]:
lr.fit(X_train, y_train)

LogisticRegression()

In [38]:
lr.coef_

array([[ 0.2017449 , -0.18115353,  0.05481345,  0.77959055,  0.13470765,
        -0.51599052, -1.25170337],
       [ 1.73241858, -0.6125848 , -0.15933959, -1.25032633, -0.03743268,
         0.1063957 ,  0.0753676 ],
       [-1.93416347,  0.79373833,  0.10452613,  0.47073578, -0.09727497,
         0.40959482,  1.17633577]])

In [40]:
y_pred = lr.predict(X_test)

In [60]:
y_test

array([3, 3, 3, 2, 3, 3, 3, 3, 2, 1, 1, 3, 3, 2, 1, 2, 1, 1, 3, 3, 2, 3,
       1, 2, 3, 1, 2, 3, 2, 3, 3, 1, 3, 3, 3, 3, 1, 2, 2, 1, 1, 3, 3, 2,
       3, 3, 3, 3, 1, 3, 3, 1, 1, 2, 2, 3, 3, 1, 2, 3, 1, 1, 2])

In [61]:
y_pred

array([3, 3, 3, 1, 3, 3, 1, 3, 2, 1, 1, 3, 3, 2, 3, 2, 1, 1, 3, 3, 2, 1,
       1, 2, 3, 1, 2, 3, 1, 3, 3, 1, 3, 3, 3, 3, 1, 2, 2, 1, 1, 3, 3, 2,
       3, 1, 3, 3, 1, 3, 3, 2, 1, 2, 2, 3, 3, 1, 2, 3, 1, 1, 2])

In [69]:
from sklearn.metrics import confusion_matrix

In [71]:
confusion_matrix(y_test, y_pred)

array([[15,  1,  1],
       [ 2, 13,  0],
       [ 3,  0, 28]])

In [72]:
y_test.shape

(63,)

In [73]:
np.sum(confusion_matrix(y_test, y_pred))

63

In [74]:
difference = map(lambda a, b: a-b, y_pred, y_test)

In [75]:
a = []
for i in y_pred:
    a += difference

In [76]:
from pprint import pprint
print(''.join(str(a)))

[0, 0, 0, -1, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
