# Function, lambda, map, filter

In [1]:
add_five = lambda a: a + 5

In [2]:
add_five(3)

8

# Map

In [3]:
lst = [2, 5, 7, 8]

In [4]:
added_5 = list(map(add_five, lst))

In [5]:
added_5

[7, 10, 12, 13]

# Filter

In [6]:
lst = list(filter(lambda a: a % 2 == 0, lst))

In [7]:
lst

[2, 8]

In [8]:
import numpy as np

In [9]:
vec = [1, 2, 3]

In [10]:
np_vec = np.array(vec)

In [11]:
np_vec

array([1, 2, 3])

In [12]:
mat = [
    [2, 6, 8],
    [3, 7, 0]
]

In [13]:
np_mat = np.array(mat)

In [14]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

# Zeros, Ones, Eye

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Random

In [18]:
np.random.randn(5)

array([-0.26045286,  1.41047627, -2.3089048 , -0.92474884,  1.30723409])

In [19]:
np.random.randn(3, 4)

array([[ 0.06783977,  0.08612209,  1.52289784,  1.41169516],
       [ 1.16257264,  0.62615817, -1.5507508 , -0.69460642],
       [-0.59550043, -0.38456499,  0.43081541,  1.52417072]])

In [20]:
np.random.randint(5, 15, 7)

array([14, 10, 14, 11, 10, 10,  6])

# Arange, linspace

In [21]:
np.arange(3, 12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(3, 12, 2)

array([ 3,  5,  7,  9, 11])

In [23]:
np.linspace(2, 10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [24]:
np.linspace(2, 10, 10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

# Shape

In [25]:
np_vec.shape

(3,)

In [26]:
np_mat.shape

(2, 3)

In [27]:
np_vec.min()

1

In [28]:
np_vec.max()

3

In [29]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [30]:
np_mat.reshape(3, 2)

array([[2, 6],
       [8, 3],
       [7, 0]])

In [31]:
np_mat.dtype

dtype('int64')

# Numpy array operations

In [32]:
a = np.array([0, 1, 2, 3, 4, 5])

In [33]:
a + 7

array([ 7,  8,  9, 10, 11, 12])

In [34]:
a * 3

array([ 0,  3,  6,  9, 12, 15])

In [35]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [36]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [37]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [38]:
np.sum(a)

15

In [39]:
np.mean(a)

2.5

In [40]:
a1 = np.array([[1, 3], [4, 6]])
b1 = np.array([[0, 2], [3, 1]])

In [41]:
a1

array([[1, 3],
       [4, 6]])

In [42]:
b1

array([[0, 2],
       [3, 1]])

In [43]:
a1 + b1

array([[1, 5],
       [7, 7]])

In [44]:
a1 - b1

array([[1, 1],
       [1, 5]])

In [45]:
a1 * b1

array([[ 0,  6],
       [12,  6]])

In [46]:
a1.dot(b1) # dot here refers to matrix multiplication

array([[ 9,  5],
       [18, 14]])

In [47]:
a

array([0, 1, 2, 3, 4, 5])

In [48]:
a > 2

array([False, False, False,  True,  True,  True])

# Indexing, slicing, broadcasting

In [49]:
d1 = np.arange(25)

In [50]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
d2 = np.arange(25).reshape(5, 5)

In [52]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
 d1[4: 12] # d1[start: end+1]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
d1[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [55]:
d1[:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
d2[0, 0] # d2[row, col]

0

In [58]:
d2[2, 1]

11

In [59]:
d2[1, :]

array([5, 6, 7, 8, 9])

In [60]:
d2[:, 3]

array([ 3,  8, 13, 18, 23])

In [61]:
d2[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [62]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
d1[0:5] = -10

In [64]:
d1

array([-10, -10, -10, -10, -10,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# Series in Pandas

In [65]:
import numpy as np
import pandas as pd

In [66]:
s1 = pd.Series([2, 6, 10], index=['a', 'b', 'c'])

In [67]:
s1['a']

2

In [68]:
pd.Series({'a1': 'Hello', 'b1': 7, 'c1': True})

a1    Hello
b1        7
c1     True
dtype: object

In [69]:
s1 = pd.Series([1, 3, 5], index=['a', 'b', 'c'])
s2 = pd.Series([2, 7, 9], index=['b', 'c', 'd'])

In [70]:
s1

a    1
b    3
c    5
dtype: int64

In [71]:
s2

b    2
c    7
d    9
dtype: int64

In [72]:
s1 * s2

a     NaN
b     6.0
c    35.0
d     NaN
dtype: float64

In [73]:
s1 - s2

a    NaN
b    1.0
c   -2.0
d    NaN
dtype: float64

# Dataframe

In [74]:
# 4.19:0:0

In [82]:
df = pd.DataFrame(data=[[2, 4, 6, -1], [3, -4, 2, -1], [-10, 3, 5, -7]], 
             columns=['C1', 'C2', 'C3', 'C4'],
             index=['R1', 'R2', 'R3'])

In [83]:
df['newC'] = df['C1'] + 5

In [84]:
df.head()

C1  C2  C3  C4  newC
R1   2   4   6  -1     7
R2   3  -4   2  -1     8
R3 -10   3   5  -7    -5

In [90]:
df.drop('newC', axis=1, inplace=True)

# Select

In [91]:
df['C1']

R1     2
R2     3
R3   -10
Name: C1, dtype: int64

In [92]:
df[['C1', 'C3']]

C1  C3
R1   2   6
R2   3   2
R3 -10   5

.loc(row, col) .iloc(row, col) integer value

In [94]:
df.loc['R2', ['C2', 'C3']]

C2   -4
C3    2
Name: R2, dtype: int64

In [96]:
df.iloc[1, 0:1]

C1    3
Name: R2, dtype: int64

In [97]:
df

C1  C2  C3  C4
R1   2   4   6  -1
R2   3  -4   2  -1
R3 -10   3   5  -7

In [102]:
df.index

Index(['R1', 'R2', 'R3'], dtype='object')

In [103]:
df.reset_index()

index  C1  C2  C3  C4
0    R1   2   4   6  -1
1    R2   3  -4   2  -1
2    R3 -10   3   5  -7

In [104]:
df.set_index('C3', inplace=True)

In [105]:
df

C1  C2  C4
C3            
6    2   4  -1
2    3  -4  -1
5  -10   3  -7

In [106]:
df.index

Int64Index([6, 2, 5], dtype='int64', name='C3')

# MultiIndex

In [108]:
df = pd.DataFrame(data=np.array([['Math', 'C1', 's1', 93],
                               ['Science', 'C1', 's2', 78],
                               ['English', 'C1', 's3', 86],
                               ['Math', 'C2', 's4', 58],
                               ['English', 'C2', 's5', 71],
                               ['Science', 'C2', 's6', 69]]), columns=['Subject', 'Class', 'Student', 'MacxScore'])

In [109]:
df

Subject Class Student MacxScore
0     Math    C1      s1        93
1  Science    C1      s2        78
2  English    C1      s3        86
3     Math    C2      s4        58
4  English    C2      s5        71
5  Science    C2      s6        69

In [110]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [112]:
df.set_index(['Class', 'Subject'], inplace=True)

In [113]:
df.index

MultiIndex([('C1',    'Math'),
            ('C1', 'Science'),
            ('C1', 'English'),
            ('C2',    'Math'),
            ('C2', 'English'),
            ('C2', 'Science')],
           names=['Class', 'Subject'])

In [116]:
df.loc['C2']

Student MacxScore
Subject                  
Math         s4        58
English      s5        71
Science      s6        69

In [117]:
df.loc['C2'].loc['English']

Student      s5
MacxScore    71
Name: English, dtype: object

# Hadling Missing Data

In [118]:
import numpy as np
import pandas as pd

In [119]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0], [3, 4, np.nan, 1],
                  [np.nan, np.nan, np.nan, 5], [np.nan, np.nan, np.nan]],
                 columns=list('ABCD'))

In [120]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  NaN NaN  NaN

In [122]:
 df.dropna(axis=1, how='all')

A    B    D
0  NaN  2.0  0.0
1  3.0  4.0  1.0
2  NaN  NaN  5.0
3  NaN  NaN  NaN

In [123]:
df.dropna(axis=0, how='any')

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [124]:
df.dropna(axis=0, how='all')

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0

In [125]:
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  5.0
3  NaN  NaN NaN  NaN

In [128]:
df['B'].fillna(df['B'].mean())

0    2.0
1    4.0
2    3.0
3    3.0
Name: B, dtype: float64

In [130]:
df.replace(0.0, 'There was 0 here')

A    B   C                 D
0  NaN  2.0 NaN  There was 0 here
1  3.0  4.0 NaN               1.0
2  NaN  NaN NaN               5.0
3  NaN  NaN NaN               NaN

In [133]:
df.replace(np.NaN, 'There was missing value here')

A                             B  \
0  There was missing value here                           2.0   
1                           3.0                           4.0   
2  There was missing value here  There was missing value here   
3  There was missing value here  There was missing value here   

                              C                             D  
0  There was missing value here                           0.0  
1  There was missing value here                           1.0  
2  There was missing value here                           5.0  
3  There was missing value here  There was missing value here

# Grouping data
# Applying Custom Function

In [134]:
import pandas as pd
import numpy as np

In [153]:
df = pd.DataFrame(data=[['MI', 'P1', 'Male', 54, 15],
                       ['MI', 'P2', 'Female', 21, 19],
                       ['DD', 'P3', 'Male', 69, 26],
                       ['RR', 'P4', 'Female', 96, 28],
                       ['GT', 'P5', 'Male', 33, 24],
                       ['MI', 'P6', 'Female', 51, 33],
                       ['KNR', 'P7', 'Male', 24, 40],
                       ['GT', 'P8', 'Male', 36, 42],
                       ['RR', 'P9', 'Female', 78, 19],
                       ['KNR', 'P10', 'Male', 33, 17],
                       ['MI', 'P11', 'Female', 87, 20],
                       ['GT', 'P12', 'Male', 81, 21],
                       ['KNR', 'P13', 'Female', 36, 29]], columns=['Team', 'Player', 'Sex', 'Score', 'Age'])

In [154]:
df

Team Player     Sex  Score  Age
0    MI     P1    Male     54   15
1    MI     P2  Female     21   19
2    DD     P3    Male     69   26
3    RR     P4  Female     96   28
4    GT     P5    Male     33   24
5    MI     P6  Female     51   33
6   KNR     P7    Male     24   40
7    GT     P8    Male     36   42
8    RR     P9  Female     78   19
9   KNR    P10    Male     33   17
10   MI    P11  Female     87   20
11   GT    P12    Male     81   21
12  KNR    P13  Female     36   29

In [155]:
df.Team.count()

13

In [156]:
df.Team.value_counts()

MI     4
GT     3
KNR    3
RR     2
DD     1
Name: Team, dtype: int64

In [157]:
df.Team.unique()

array(['MI', 'DD', 'RR', 'GT', 'KNR'], dtype=object)

In [158]:
df.Team.nunique()

5

In [159]:
by_team = df.groupby('Team')

In [160]:
by_team.sum()

/var/folders/cq/xb4738d94n3gn3zljsgyvvnh0000gp/T/ipykernel_724/1894735241.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_team.sum()


Score  Age
Team            
DD       69   26
GT      150   87
KNR      93   86
MI      213   87
RR      174   47

In [161]:
by_team.mean()

/var/folders/cq/xb4738d94n3gn3zljsgyvvnh0000gp/T/ipykernel_724/628173305.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_team.mean()


Score        Age
Team                  
DD    69.00  26.000000
GT    50.00  29.000000
KNR   31.00  28.666667
MI    53.25  21.750000
RR    87.00  23.500000

In [162]:
df.groupby('Sex').sum()

/var/folders/cq/xb4738d94n3gn3zljsgyvvnh0000gp/T/ipykernel_724/3906318127.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Sex').sum()


Score  Age
Sex               
Female    369  148
Male      330  185

In [163]:
df.groupby('Team').describe()

Score                                                    Age             \
     count   mean        std   min   25%   50%    75%   max count       mean   
Team                                                                           
DD     1.0  69.00        NaN  69.0  69.0  69.0  69.00  69.0   1.0  26.000000   
GT     3.0  50.00  26.888659  33.0  34.5  36.0  58.50  81.0   3.0  29.000000   
KNR    3.0  31.00   6.244998  24.0  28.5  33.0  34.50  36.0   3.0  28.666667   
MI     4.0  53.25  26.986108  21.0  43.5  52.5  62.25  87.0   4.0  21.750000   
RR     2.0  87.00  12.727922  78.0  82.5  87.0  91.50  96.0   2.0  23.500000   

                                                 
            std   min    25%   50%    75%   max  
Team                                             
DD          NaN  26.0  26.00  26.0  26.00  26.0  
GT    11.357817  21.0  22.50  24.0  33.00  42.0  
KNR   11.503623  17.0  23.00  29.0  34.50  40.0  
MI     7.804913  15.0  18.00  19.5  23.25  33.0  
RR     6.363961  19.0  21.25  23.5  25.75  28.0

In [165]:
df

Team Player     Sex  Score  Age
0    MI     P1    Male     54   15
1    MI     P2  Female     21   19
2    DD     P3    Male     69   26
3    RR     P4  Female     96   28
4    GT     P5    Male     33   24
5    MI     P6  Female     51   33
6   KNR     P7    Male     24   40
7    GT     P8    Male     36   42
8    RR     P9  Female     78   19
9   KNR    P10    Male     33   17
10   MI    P11  Female     87   20
11   GT    P12    Male     81   21
12  KNR    P13  Female     36   29

In [168]:
def congrats(x):
    if x > 70:
        return "Congratulation "
    else:
        return ""

In [169]:
df.Score.apply(congrats)

0                    
1                    
2                    
3     Congratulation 
4                    
5                    
6                    
7                    
8     Congratulation 
9                    
10    Congratulation 
11    Congratulation 
12                   
Name: Score, dtype: object

In [170]:
df.Player = df.Score.apply(congrats) + df.Player

In [171]:
df

Team              Player     Sex  Score  Age
0    MI                  P1    Male     54   15
1    MI                  P2  Female     21   19
2    DD                  P3    Male     69   26
3    RR   Congratulation P4  Female     96   28
4    GT                  P5    Male     33   24
5    MI                  P6  Female     51   33
6   KNR                  P7    Male     24   40
7    GT                  P8    Male     36   42
8    RR   Congratulation P9  Female     78   19
9   KNR                 P10    Male     33   17
10   MI  Congratulation P11  Female     87   20
11   GT  Congratulation P12    Male     81   21
12  KNR                 P13  Female     36   29